# permissions for end users to view dataviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataview-viewer-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews/status
  verbs:
  - get
