# permissions for end users to edit dataviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataview-editor-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - dataviews/status
  verbs:
  - get
