# permissions for end users to edit elasticsearchusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchapikey-editor-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchapikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchapikeys/status
  verbs:
  - get
