# permissions for end users to view elasticsearchusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchuser-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchusers/status
  verbs:
  - get
