# permissions for end users to view elasticsearchroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticsearchrole-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - elasticsearchroles/status
  verbs:
  - get
