# permissions for end users to view indices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: index-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - indices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - indices/status
  verbs:
  - get
