# permissions for end users to view indexpatterns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: indexpattern-viewer-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - indexpatterns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - indexpatterns/status
  verbs:
  - get
