# permissions for end users to view ingestpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingestpipeline-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines/status
  verbs:
  - get
