# permissions for end users to edit ingestpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingestpipeline-editor-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - ingestpipelines/status
  verbs:
  - get
