# permissions for end users to view lens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lens-viewer-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - lens/status
  verbs:
  - get
