# permissions for end users to view savedsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: savedsearch-viewer-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches/status
  verbs:
  - get
