# permissions for end users to edit savedsearches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: savedsearch-editor-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - savedsearches/status
  verbs:
  - get
