# permissions for end users to edit snapshotlifecyclepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotlifecyclepolicy-editor-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotlifecyclepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotlifecyclepolicies/status
  verbs:
  - get
