# permissions for end users to view snapshotrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotrepository-viewer-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories/status
  verbs:
  - get
