# permissions for end users to edit snapshotrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotrepository-editor-role
rules:
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.eck.github.com
  resources:
  - snapshotrepositories/status
  verbs:
  - get
