# permissions for end users to edit visualizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visualization-editor-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations/status
  verbs:
  - get
