# permissions for end users to view visualizations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: visualization-viewer-role
rules:
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kibana.eck.github.com
  resources:
  - visualizations/status
  verbs:
  - get
