---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    name: {{ .Release.Name }}-config
data:
  operator_config.yaml: |-
    type:
      apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
      kind: ControllerManagerConfig
    manager:
      health:
        healthProbeBindAddress: :{{ .Values.manager.health.healthProbePort }}
      metrics:
        bindAddress: :{{ .Values.metrics.service.port }}
      webhook:
        port: {{ .Values.manager.webhook.port }}
      leaderElection:
        leaderElect: {{ .Values.manager.leaderElection.leaderElect }}
        resourceName: eck-custom-resources.xco-sk.github.com
    
    elasticsearch:
      enabled: {{ .Values.elasticsearch.enabled }}
      url: {{ .Values.elasticsearch.url }}
      certificate:
        secretName: {{ .Values.elasticsearch.certificate.secretName }}
        certificateKey: {{ .Values.elasticsearch.certificate.certificateKey }}
      authentication:
        usernamePasswordSecret:
          secretName: {{ .Values.elasticsearch.authentication.usernamePasswordSecret.secretName }}
          userName: {{ .Values.elasticsearch.authentication.usernamePasswordSecret.userName }}
    
    kibana:
      enabled: {{ .Values.kibana.enabled }}
      url: {{ .Values.kibana.url }}
      certificate:
        secretName: {{ .Values.kibana.certificate.secretName }}
        certificateKey: {{ .Values.kibana.certificate.certificateKey }}
      authentication:
        usernamePasswordSecret:
          secretName: {{ .Values.kibana.authentication.usernamePasswordSecret.secretName }}
          userName: {{ .Values.kibana.authentication.usernamePasswordSecret.userName }}
