{{- if .Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "eck-custom-resources-operator.clusterRoleName" . }}-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "eck-custom-resources-operator.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "eck-custom-resources-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
